Task 1
Pavel545/trying-to-make-the-coursework-better pull request #4
Opened 2022-08-25 10:25 UTC by Pavel545

2022-08-28 09:32 UTC, mrerberg requested changes

2022-08-28 09:32 UTC, mrerberg commented on .gitignore
> +
Что за отступы? Почему папки dist  тут нет?

2022-08-28 09:32 UTC, mrerberg commented on scr/index.js
> +import  './static/6.1.png';
Реши этот вопрос через статические файлы 

https://stackoverflow.com/questions/34870888/serving-static-assets-in-webpack-dev-server

2022-08-28 09:32 UTC, mrerberg commented on scr/index.js
> +import  './static/6.1.png';
Чтобы не приходилось кучу импортов делать

2022-08-29 06:52 UTC, mrerberg requested changes

2022-08-29 06:52 UTC, mrerberg commented on scr/template.js
> +window.templateEngine = function (block) {
А зачем ты присваиваешь в глобальную переменную? Это не есть хорошо, нет такой необходимости

2022-08-29 06:52 UTC, mrerberg commented on scr/application.js
> +//Массив в котором пречисленны id карт, для удобства сравнения и отображения, каждый элемент массива соответствует определённой карте
Ты же можешь задать специальный атрибут в html карте, типа data-id, data-card-id и таким образом получать его, когда нужно сравнить. Вместо того, чтобы хранить этот массив

2022-08-29 06:52 UTC, mrerberg commented on package.json
> +        "lint:css": "stylelint scr/style/style.css",
Папка неправильно называется, надо src, а не scr

2022-08-29 06:52 UTC, mrerberg commented on package.json
> +        "lint:css": "stylelint scr/style/style.css",
У тебя исходники не в css, а scss

2022-08-29 06:52 UTC, mrerberg commented on index.html
> +    <script src="scr/application.js"></script>
Эти скрипты не надо подключать самому, это сделает вебпак

2022-08-29 09:30 UTC, Pavel545 commented on index.html
> +    <script src="scr/application.js"></script>
это тока в корневом index  его не затрагивает вебпак, значит его(index что находится в корне) просто совсем удалить?

2022-08-29 10:46 UTC, Pavel545 commented on scr/application.js
> +//Массив в котором пречисленны id карт, для удобства сравнения и отображения, каждый элемент массива соответствует определённой карте
у меня же просто изображения которые полностью удаляются при переворачивании так шо с этим возникнут трудности

2022-08-29 12:08 UTC, Pavel545 commented on scr/template.js
> +window.templateEngine = function (block) {
если только удалить кореневой Index  и спользовать только то что скомпилирует веб пак так делать?

2022-08-29 12:09 UTC, Pavel545 commented on package.json
> +        "lint:css": "stylelint scr/style/style.css",
https://github.com/stylelint-scss/stylelint-scss/issues/104
понятнее наверно проверять то что используется приложением а не исходник

2022-08-30 06:24 UTC, mrerberg requested changes

2022-08-30 06:24 UTC, mrerberg commented on src/style/style.css
> +/* stylelint-disable declaration-block-no-duplicate-properties */
Эти файлы у тебя не исходники. В src должны лежать лишь исходники (sass). Далее, вебпак должен компилировать исходники в готовый код и класть в dist

2022-08-30 06:52 UTC, closed without merging