Correction
Pavel545/trying-to-make-the-coursework-better pull request #7
Opened 2022-08-30 09:04 UTC by Pavel545

2022-09-01 06:19 UTC, mrerberg requested changes

2022-09-01 06:19 UTC, mrerberg commented on package.json
> +        "http-server": "^14.1.1",
Зачем тебе нужен данный пакет?

2022-09-01 06:19 UTC, mrerberg commented on package.json
> +        "postcss-sass": "^0.5.0"
почему это не dev dependency?

2022-09-01 06:19 UTC, mrerberg commented on src/application.js
> +window.static = "./src/static"
В обычную константу, зачем в глобальную область видимости то записывать?

2022-09-01 06:19 UTC, mrerberg commented on src/block_layout.js
> +    for (let i = 1; i < 3; i ++) {
Что за число 3?

2022-09-01 06:19 UTC, mrerberg commented on src/block_layout.js
> +        for (let j = 6; j < 6+count; j++) {
Что за число 6?

2022-09-01 07:41 UTC, mrerberg requested changes

2022-09-01 07:41 UTC, mrerberg commented on package.json
> +        "lint": "",
Зачем тебе пустая строка тут?

2022-09-01 07:41 UTC, mrerberg commented on src/block_layout.js
> +const staticFiles = './src/static'
Глобальные константы пишутся через UPPER_SNAKE_CASE и рекомендую вынести в файлик с названием constants

2022-09-01 07:41 UTC, mrerberg commented on src/block_layout.js
> +    const suit=3 //так как с максимальной сложностью карт не более 18 то на вывод карты не более 2х мастей
Почему не более 2х мастей?

2022-09-01 07:41 UTC, mrerberg commented on src/block_layout.js
> +    const step = 6//номер карт начинаются с 6, поэтому нужно немного так сказать отступить от 0
Вместо комментариев лучше постараться придумать описательное название переменной

2022-09-01 09:24 UTC, Pavel545 commented on src/block_layout.js
> +    const suit=3 //так как с максимальной сложностью карт не более 18 то на вывод карты не более 2х мастей
"так как с максимальной сложностью карт не более 18" по парам карт 2 масти красивее всего так сказать

2022-09-01 10:02 UTC, Pavel545 commented on src/block_layout.js
> +    const suit=3 //так как с максимальной сложностью карт не более 18 то на вывод карты не более 2х мастей
так как с максимальной сложностью карт не более 18

2022-09-02 07:20 UTC, mrerberg requested changes

2022-09-02 07:20 UTC, mrerberg commented on src/block_layout.js
> +    const suit=3 //так как с максимальной сложностью карт не более 18 то на вывод, более чем достаточно карт 2-х мастей
Стоит число 3, а в описании указаны 2 масти. Кому верить?

2022-09-02 07:20 UTC, mrerberg commented on src/game_process.js
> +winDifficult = 18;
Это переменные, которые хранят количество совпадений для выигрыша?  Если так, то либо стоит придумать более понятное название переменным, либо занести эти числа в конфиг игры. Таким образом, мы сможем использовать эти данные как для генерации карт, так и для проверки в конце игры

2022-09-02 08:47 UTC, Pavel545 commented on src/block_layout.js
> +    const suit=3 //так как с максимальной сложностью карт не более 18 то на вывод, более чем достаточно карт 2-х мастей
просто в условии цикла меньше 3х, если приравнивать к 2м то не работат не чё

2022-09-04 10:03 UTC, mrerberg requested changes

2022-09-04 10:03 UTC, mrerberg commented on .husky/pre-commit
> -npm run lint
А почему убрал?

2022-09-04 10:03 UTC, mrerberg commented on package.json
> -        "lint": "",
А почему ты убрал команду? Почему у тебя нет настройки линтинга скритов eslint?

2022-09-04 10:04 UTC, mrerberg requested changes

2022-09-04 10:04 UTC, mrerberg commented on src/game_process.js
> +            if (countersWin === NUMBER_MATCHES_EASE && window.complexity === 'easy') {
Значения сложности можно тоже вынести в константы

'easy',  'average', 'difficult'

2022-09-04 13:54 UTC, Pavel545 commented on .husky/pre-commit
> -npm run lint
потому что так и не решили как делать с sass

2022-09-05 06:22 UTC, mrerberg approved these changes

2022-09-05 06:22 UTC, mrerberg commented on package.json
> +        "lint:js": "npx eslint src/**.js",
eslint src/**/*.js

2022-09-05 06:22 UTC, mrerberg commented on package.json
> +        "lint": "npm run lint:js     & npm run lint:sass",
Лишние пробелы

2022-09-06 09:26 UTC, merged